# fly.toml app configuration file generated for todo-extractor on 2023-06-28T17:06:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todo-extractor"
primary_region = "ams"

[build]
  dockerfile = "apps/todo_extractor/chainlit.Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
